name: Tag, Build, and Publish Container

on:
  push:
    branch: "master"

jobs:
  tag-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get version for tag
        run: |
          echo "VERSION=$(awk -F '=' '/TOR_VERSION/{print $NF; exit}' Dockerfile | tr -d '"')" >> $GITHUB_ENV

      - name: Create version tag
        uses: rickstaa/action-create-tag@v1
        with:
          force_push_tag: true
          tag: "${{ env.VERSION }}"
          message: "Tor Browser v${{ env.VERSION }}"

      - name: Tag as latest
        uses: rickstaa/action-create-tag@v1
        with:
          force_push_tag: true
          tag: "latest"
          message: "Latest Tor Browser version"
      
      - name: Set up QEMU  # for arm support
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            domistyle/tor-browser:${{ env.VERSION }}
            domistyle/tor-browser:latest
            ghcr.io/domistyle/tor-browser:${{ env.VERSION }}
            ghcr.io/domistyle/tor-browser:latest